Aktualisiertes englisches Sprach-Bundle von Christian und aktualisiertes Init-Script fuer CentOS

diff --git a/build/rcjameica-centos b/build/rcjameica-centos
--- a/build/rcjameica-centos
+++ b/build/rcjameica-centos
@@ -4,9 +4,9 @@
 
 
 #
-# Name         : Jameica Server Daemon
+# Name         : Jameica Server Daemon für Hibiscus-Server
 #
-# Version      : 1.0 (06.2015)
+# Version      : 1.0.1 (08.2015)
 #
 # 
 #
@@ -23,7 +23,7 @@
 #                entwickelt und optimiert, und dient hier in erster Linie dem Betrieb eines
 #                dedizierten Hibiscus HBCI Payment Servers als Plugin der Jameica-Plattform.
 #
-# Autor        : Christian B. Caldarone
+# Autor        : Christian B. Caldarone <caldarone@gmx.net>
 #
 
 
@@ -46,7 +46,7 @@ DAEMON_USER="jameica"
 
 # Vollständiger Pfad zum Shell Start-Script für den Jameica-Server
 
-JAMEICA_CMD="/opt/jameica/jameicaserver.sh"
+JAMEICA_CMD="/opt/hibiscus-server/jameicaserver.sh"
 
 
 # Zeichenkette um den Jameica Server in der Liste laufender Prozesse identifizieren zu können,
@@ -57,7 +57,7 @@ JAMEICA="jameica-linux.jar"
 
 # Freundlicher Name, wird für Ausgabe-Meldungen dieses Scripts verwendet und hat rein beschreibenden Charakter 
 
-FRIENDLY_NAME="Jameica-Server"
+FRIENDLY_NAME="Hibiscus-Server"
 
 
 # Diese Zeichenfolge muss genau so lauten, wie der Dateiname dieses Scripts, wird verwendet um den Koventionen
@@ -95,93 +95,95 @@ JAMEICA_PID="$(pgrep -u $DAEMON_USER -f $JAMEICA 2>/dev/null)"
 # ----------------------------------------------------
 
 start() { 
-  # Prüfen ob das Shell Start-Script für den Jameica-Server existiert und ausführbar ist, wenn nicht, direkt mit Fehler zurück
+	# Prüfen ob das Shell Start-Script für den Jameica-Server existiert und ausführbar ist, wenn nicht, direkt mit Fehler zurück
 
-  if [ ! -x $JAMEICA_CMD ]; then
+	if [ ! -x $JAMEICA_CMD ]; then
 
-    verbosity "Datei '$JAMEICA_CMD' existiert nicht oder ist nicht ausführbar. Abbruch.\n"
-    return 1
+		verbosity "Datei '$JAMEICA_CMD' existiert nicht oder ist nicht ausführbar. Abbruch.\n"
+		return 1
 
-  fi
+	fi
 
-  
-  # Nun prüfen ob Jameica schon ein PID hat, d.h. schon läuft
+	
+	# Nun prüfen ob Jameica schon ein PID hat, d.h. schon läuft
 
-  if [ "$JAMEICA_PID" == ""  ]; then # Der Jameica Server läuft noch nicht, also starten ...
+	if [ "$JAMEICA_PID" == ""  ]; then # Der Jameica Server läuft noch nicht, also starten ...
+		
+		# Der Jameica Server wird als Daemon-Prozess im Hintergrund unter dem Benutzer aus '$DAEMON_USER' gestartet
+
+		verbosity "$FRIENDLY_NAME wird nun unter Benutzer '$DAEMON_USER' gestartet\n"
+
+		[ $verbose -gt 0 ] || echo -n "Starting $FRIENDLY_NAME:"
+
+		daemon --user $DAEMON_USER $JAMEICA_CMD >/dev/null 2>&1 &
+
+		# Rückgabewert des Starts des Daemon-Prozesses zwischenspeichern 
+
+		retval=$?
+		
+		# Maximale Wartezeit in Sekunden für den vollständigen Start des Jameica Servers festlegen 
+
+		waittime=30
+
+		# Anfangszähler auf Null setzen
+
+    		count=0
+
+		# Warte nun bis der Jameica Server gestartet ist, oder die maximale Wartezeit erreicht ist
+
+		verbosity "Warten bis $FRIENDLY_NAME gestartet wurde...\n"
+
+		until [ ! "$JAMEICA_PID" == "" ] || [ $count -gt $waittime ]
     
-    # Der Jameica Server wird als Daemon-Prozess im Hintergrund unter dem Benutzer aus '$DAEMON_USER' gestartet
+		do
 
-    verbosity "$FRIENDLY_NAME wird nun unter Benutzer '$DAEMON_USER' gestartet\n"
+			# Im Abstand einer Sekunde prüfen, ob der Jameica Server Prozess gestartet ist,
+			# d.h. ob der Prozess eine PID zurückgibt
 
-    daemon --user $DAEMON_USER $JAMEICA_CMD >/dev/null 2>&1 &
+      			JAMEICA_PID="$(pgrep -u $DAEMON_USER -f $JAMEICA 2>/dev/null)"
+			sleep 1
+      			let count=$count+1
 
-    # Rückgabewert des Starts des Daemon-Prozesses zwischenspeichern 
-
-    retval=$?
-    
-    # Maximale Wartezeit in Sekunden für den vollständigen Start des Jameica Servers festlegen 
-
-    waittime=30
-
-    # Anfangszähler auf Null setzen
-
-        count=0
-
-    # Warte nun bis der Jameica Server gestartet ist, oder die maximale Wartezeit erreicht ist
-
-    verbosity "Warten bis $FRIENDLY_NAME gestartet wurde...\n"
-
-    until [ ! "$JAMEICA_PID" == "" ] || [ $count -gt $waittime ]
-    
-    do
-
-      # Im Abstand einer Sekunde prüfen, ob der Jameica Server Prozess gestartet ist,
-      # d.h. ob der Prozess eine PID zurückgibt
-
-            JAMEICA_PID="$(pgrep -u $DAEMON_USER -f $JAMEICA 2>/dev/null)"
-      sleep 1
-            let count=$count+1
-
-        done
+    		done
  
-    # Konnte der Prozess nicht erfolgreich innerhalb der max. Wartezeit gestartet werden,
-    # dann direkt mit Time-out Fehler beenden
+		# Konnte der Prozess nicht erfolgreich innerhalb der max. Wartezeit gestartet werden,
+		# dann direkt mit Fehler beenden
 
-        if [ $count -gt $waittime ]; then
+    		if [ $count -gt $waittime ]; then
 
-      verbosity "Time out!\n"
-      verbosity "Der Prozess $FRIENDLY_NAME konnte nicht innerhalb von "$count"s gestartet werden\n"
-      return 1
+			verbosity "Time out!\n"
+			verbosity "Der Prozess $FRIENDLY_NAME konnte nicht innerhalb von "$count"s gestartet werden\n"
+			return 1
 
-    fi
-            
+		fi
+      			
 
-    # Wurde der Prozess erfolgreich gestartet, dann Lock-File und PID-File schreiben
-    
-    if [ $retval -eq 0 ]; then
+		# Wurde der Prozess erfolgreich gestartet, dann Lock-File und PID-File schreiben
+		
+		if [ $retval -eq 0 ]; then
 
-      touch $lockfile
-      verbosity "Erstellt: $lockfile\n"
-      echo "$(pgrep -u $DAEMON_USER -f $JAMEICA)" > $pidfile
-      verbosity "Erstellt: $pidfile\n"
-      verbosity "$FRIENDLY_NAME wurde innerhalb von "$count"s erfolgreich gestartet\n"
-      
-    fi
+			touch $lockfile
+			verbosity "Erstellt: $lockfile\n"
+			echo "$(pgrep -u $DAEMON_USER -f $JAMEICA)" > $pidfile
+			verbosity "Erstellt: $pidfile\n"
+			verbosity "$FRIENDLY_NAME wurde innerhalb von "$count"s erfolgreich gestartet\n"
+			
+		fi
 
-  
+	
 
-  else # Für den Fall, dass oben festgestellt wurde, dass Jameica schon ein PID hat, d.h. schon läuft
+	else # Für den Fall, dass oben festgestellt wurde, dass Jameica schon ein PID hat, d.h. schon läuft
 
-    # ...ausgeben, mit welcher PID der Jameica Server läuft
+		# ...ausgeben, mit welcher PID der Jameica Server läuft
 
-    verbosity "$FRIENDLY_NAME$(status -p $pidfile)\n"
-        
+		verbosity "$FRIENDLY_NAME$(status -p $pidfile)\n"
+				
 
-  fi
-    
-  # Unterprogramm mit Rückgabewert beenden
+	fi
+		
+	# Unterprogramm mit Rückgabewert beenden
 
-      return $retval
+    	return $retval
 }
 
 
@@ -192,79 +194,81 @@ start() {
 
 stop() {
 
-  # Prüfen anhand der PID, ob der Jameica Server überhaupt läuft
+	# Prüfen anhand der PID, ob der Jameica Server überhaupt läuft
 
-  if [ "$JAMEICA_PID" == ""  ]; then # ...wenn nicht, direkt zurück, da er bereits gestoppt ist 
-      
-    verbosity "$FRIENDLY_NAME ist bereits beendet\n"
-    return 0
+	if [ "$JAMEICA_PID" == ""  ]; then # ...wenn nicht, direkt zurück, da er bereits gestoppt ist 
+			
+		verbosity "$FRIENDLY_NAME ist bereits beendet\n"
+		return 0
 
-  else # wenn doch, dann den Prozess beenden
+	else # wenn doch, dann den Prozess beenden
 
+		
+		# Mit killproc über PID-File als präferierte Methode beenden
+
+		killproc -p $pidfile >/dev/null 2>&1
+		
+		retval=$?
+		
+		verbosity "$FRIENDLY_NAME wird nun beendet\n"
+
+		[ $verbose -gt 0 ] || echo -n "Stopping $FRIENDLY_NAME:"
+
+		# Maximale Wartezeit in Sekunden für das vollständige Beenden des Jameica Servers festlegen
+
+		waittime=30
+
+		# Anfangszähler auf Null setzen
+
+    		count=0
+
+		# Warte nun bis der Jameica Server beendet ist, oder die maximale Wartezeit erreicht ist 
+
+		verbosity "Warten bis $FRIENDLY_NAME beendet ist...\n"
+
+		until [ "$JAMEICA_PID" == "" ] || [ $count -gt $waittime ]
     
-    # Mit killproc über PID-File als präferierte Methode beenden
+		do
 
-    killproc -p $pidfile >/dev/null 2>&1
-    
-    retval=$?
-    
-    verbosity "$FRIENDLY_NAME wird nun beendet\n"
+			# Im Abstand einer Sekunde prüfen, ob der Jameica Server Prozess noch läuft,
+			# d.h. ob der Prozess immer noch eine PID zurückgibt
 
-    # Maximale Wartezeit in Sekunden für das vollständige Beenden des Jameica Servers festlegen
+      			JAMEICA_PID="$(pgrep -u $DAEMON_USER -f $JAMEICA 2>/dev/null)"
+			sleep 1
+      			let count=$count+1;
 
-    waittime=30
+    		done
 
-    # Anfangszähler auf Null setzen
-
-        count=0
-
-    # Warte nun bis der Jameica Server beendet ist, oder die maximale Wartezeit erreicht ist 
-
-    verbosity "Warten bis $FRIENDLY_NAME beendet ist...\n"
-
-    until [ "$JAMEICA_PID" == "" ] || [ $count -gt $waittime ]
-    
-    do
-
-      # Im Abstand einer Sekunde prüfen, ob der Jameica Server Prozess noch läuft,
-      # d.h. ob der Prozess immer noch eine PID zurückgibt
-
-            JAMEICA_PID="$(pgrep -u $DAEMON_USER -f $JAMEICA 2>/dev/null)"
-      sleep 1
-            let count=$count+1;
-
-        done
-
-    # Konnte der Prozess nicht erfolgreich innerhalb der max. Wartezeit beendet werden,
-    # dann direkt mit Time-Out Fehler beenden
+		# Konnte der Prozess nicht erfolgreich innerhalb der max. Wartezeit beendet werden,
+		# dann wegen Time-Out beenden
  
-        if [ $count -gt $waittime ]; then
+    		if [ $count -gt $waittime ]; then
 
-      retval=1
-      verbosity "Time out!\n"
-      verbosity "$FRIENDLY_NAME konnte nicht innerhalb von "$count"s beendet werden\n"
-      return 1
+			retval=1
+			verbosity "Time out!\n"
+			verbosity "$FRIENDLY_NAME konnte nicht innerhalb von "$count"s beendet werden\n"
+			return 1
 
-    fi
+		fi
+		
+		# Wurde der Prozess erfolgreich beendet, dann Lock-File und PID-File löschen
+
+		if [ $retval -eq 0 ]; then
+
+			rm -f $lockfile
+			verbosity "Gelöscht: $lockfile\n"
+			rm -f $pidfile
+			verbosity "Gelöscht: $pidfile\n"
+			verbosity "$FRIENDLY_NAME wurde innerhalb von "$count"s beendet\n"
+			
+		fi
+	
     
-    # Wurde der Prozess erfolgreich beendet, dann Lock-File und PID-File löschen
+    	fi
 
-    if [ $retval -eq 0 ]; then
-
-      rm -f $lockfile
-      verbosity "Gelöscht: $lockfile\n"
-      rm -f $pidfile
-      verbosity "Gelöscht: $pidfile\n"
-      verbosity "$FRIENDLY_NAME wurde innerhalb von "$count"s beendet\n"
-      
-    fi
-  
+	# Unterprogramm mit Rückgabewert beenden
     
-      fi
-
-  # Unterprogramm mit Rückgabewert beenden
-    
-      return $retval
+    	return $retval
 }
 
 
@@ -274,9 +278,9 @@ stop() {
 
 restart() {
 
-    
-    stop
-    start
+		
+		stop
+		start
 
 }
 
@@ -287,19 +291,19 @@ restart() {
 
 get_status() {
 
-    verbosity "Prozessname   : $proc\n"
-    verbosity "Anzeigename   : $FRIENDLY_NAME\n"
-    verbosity "Benutzer      : $DAEMON_USER\n"
-    verbosity "Hauptprogramm : $JAMEICA_CMD\n"
-    
-    [ ! -e $lockfile ] || verbosity "Lockfile      : $lockfile\n"
+		verbosity "Prozessname   : $proc\n"
+		verbosity "Anzeigename   : $FRIENDLY_NAME\n"
+		verbosity "Benutzer      : $DAEMON_USER\n"
+		verbosity "Hauptprogramm : $JAMEICA_CMD\n"
+		
+		[ ! -e $lockfile ] || verbosity "Lockfile      : $lockfile\n"
 
-    [ ! -e $pidfile ] || verbosity "Pidfile       : $pidfile\n"
-    
-    verbosity "Status        : "
+		[ ! -e $pidfile ] || verbosity "Pidfile       : $pidfile\n"
+		
+		verbosity "Status        : "
 
-    echo "$FRIENDLY_NAME" $(status -p $pidfile)
-    
+		echo "$FRIENDLY_NAME" $(status -p $pidfile)
+		
 }
 
 
@@ -311,7 +315,7 @@ verbosity() {
 
 if [ $verbose -gt 0 ]; then
 
-  echo -ne "[$proc] $*"
+	echo -ne "[$proc] $*"
 
 fi
 
@@ -325,9 +329,9 @@ fi
 
 check_user() {
 
-    DAEMON_USER_UID=$(id -u $DAEMON_USER 2>/dev/null)
+		DAEMON_USER_UID=$(id -u $DAEMON_USER 2>/dev/null)
 
-    [ $DAEMON_USER_UID ] || { verbosity "Benutzer '$DAEMON_USER' existiert nicht. Abbruch.\n" ; exit 1 ; }
+		[ $DAEMON_USER_UID ] || { verbosity "Benutzer '$DAEMON_USER' existiert nicht. Abbruch.\n" ; exit 1 ; }
 
 }
 
@@ -341,61 +345,62 @@ check_user() {
 
 case "$2" in
 
-    -v|--verbose)
-      verbose=1
-      verbosity "Ausgabe aller Meldungen mit '-v' oder '--verbose' aktiviert.\n"
-    ;;
+		-v|--verbose)
+			verbose=1
+			verbosity "Ausgabe aller Meldungen mit '-v' oder '--verbose' aktiviert.\n"
+		;;
 
 esac
 
 case "$1" in
     
-    start)
-      check_user
-      $1
-      retval=$?
-    ;;
+		start)
+			check_user
+			$1
+			retval=$?
+		;;
 
-    stop)
-      check_user
-      $1
-      retval=$?
-    ;;
-    
-    restart)
-      check_user
-      $1
-      retval=$?
-    ;;
-    status)
-      check_user
-      get_status
-      exit 0
-    ;;
+		stop)
+			check_user
+			$1
+			retval=$?
+		;;
+		
+		restart)
+			check_user
+			$1
+			retval=$?
+		;;
+		status)
+			check_user
+			get_status
+			exit 0
+		;;
 
-    *)
-            echo $"Usage: $0 {start|stop|status|restart}"
-            exit 2
+		*)
+        		echo $"Usage: $0 {start|stop|status|restart}"
+        		exit 2
 
 esac
 
 
-# Ende des Init-Scripts mit Ausgabe [  OK  ] oder [FAILED] anhand Rückgabewert von 'retval'
+# Ende des Init-Scripts mit Ausgabe [  OK  ] oder [FAILED] anhand Rückgabewert von $retval
 
 if [ "$retval" = "0" ] || [ "$retval" = "" ]; then
 
-  success
-  echo
-  exit 0
+	success
+	echo
+	exit 0
 
 else
 
-  failure
-  echo
-  exit 1
+	failure
+	echo
+	exit 1
 
 fi
 
 
 exit
+
 
